{"error":"Internal server error","details":"[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image-preview:generateContent: [400 Bad Request] Invalid value at 'contents[0].parts[1].inline_data' (data), Starting an object on a scalar field\nInvalid value at 'contents[0].parts[2].inline_data' (data), Starting an object on a scalar field [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"contents[0].parts[1].inline_data\",\"description\":\"Invalid value at 'contents[0].parts[1].inline_data' (data), Starting an object on a scalar field\"},{\"field\":\"contents[0].parts[2].inline_data\",\"description\":\"Invalid value at 'contents[0].parts[2].inline_data' (data), Starting an object on a scalar field\"}]}]"}